import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpFromLine,
  Ban,
  Banknote,
  Bell,
  BellOff,
  Building2,
  Calendar,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleX,
  ClipboardList,
  Clock,
  Download,
  Ellipsis,
  FileImage,
  FileText,
  Globe,
  House,
  IdCard,
  Image,
  ImageUp,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  Lock,
  LogOut,
  MailCheck,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  MousePointerClick,
  NotebookPen,
  Package,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Phone,
  Play,
  Plus,
  Printer,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  "trash-2": Trash2,
  "smile": Smile,
  "save": Save,
  "x": X,
  "message-circle": MessageCircle,
  "check": Check,
  "send": Send,
  "plus": Plus,
  "user": User,
  "chevron-right": ChevronRight,
  "banknote": Banknote,
  "stethoscope": Stethoscope,
  "package": Package,
  "moon": Moon,
  "map-pin": MapPin,
  "clock": Clock,
  "chevron-down": ChevronDown,
  "wallet": Wallet,
  "triangle-alert": TriangleAlert,
  "sun": Sun,
  "menu": Menu,
  "circle-check": CircleCheck,
  "bell": Bell,
  "users": Users,
  "shield-check": ShieldCheck,
  "search": Search,
  "rotate-ccw": RotateCcw,
  "printer": Printer,
  "palette": Palette,
  "minus": Minus,
  "image-up": ImageUp,
  "download": Download,
  "clipboard-list": ClipboardList,
  "calendar-x": CalendarX,
  "calendar-plus": CalendarPlus,
  "ban": Ban,
  "arrow-left": ArrowLeft,
  "upload": Upload,
  "sparkles": Sparkles,
  "settings": Settings,
  "id-card": IdCard,
  "circle-x": CircleX,
  "chevron-left": ChevronLeft,
  "chart-column": ChartColumn,
  "calendar-days": CalendarDays,
  "user-plus": UserPlus,
  "tag": Tag,
  "star": Star,
  "share-2": Share2,
  "play": Play,
  "phone": Phone,
  "pause": Pause,
  "log-out": LogOut,
  "lock": Lock,
  "inbox": Inbox,
  "house": House,
  "file-text": FileText,
  "file-image": FileImage,
  "chevron-up": ChevronUp,
  "calendar": Calendar,
  "building-2": Building2,
  "bell-off": BellOff,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-right": ArrowRight,
  "arrow-down-to-line": ArrowDownToLine,
  "wrench": Wrench,
  "smartphone": Smartphone,
  "panel-left-open": PanelLeftOpen,
  "panel-left-close": PanelLeftClose,
  "notebook-pen": NotebookPen,
  "mouse-pointer-click": MousePointerClick,
  "mail-check": MailCheck,
  "layout-dashboard": LayoutDashboard,
  "key-round": KeyRound,
  "info": Info,
  "image": Image,
  "globe": Globe,
  "ellipsis": Ellipsis,
  "camera": Camera,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Icono de línea (Lucide). El nombre es tipado: añadir aquí los nuevos que se necesiten. */
export default function Icon({ name, size = 20, style, className }: { name: IconName; size?: number; style?: React.CSSProperties; className?: string }) {
  const C = ICONS[name];
  return <C size={size} strokeWidth={2} aria-hidden="true" style={{ flexShrink: 0, ...style }} className={className} />;
}
